config/routes.rb
Rails.application.routes.draw do
  resources :trips

end

app/models/trip.rb
class Trip < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  # TODO api呼び出し時にCSRFトークンを持たせる
  protect_from_forgery with: :null_session
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:title, :description, :from_date, :to_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title= 'hermes'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body

    header.header.l-header
      .header__inner.l-header-inner
        h2.header__logo HERMES

        ul.header-menu
          li.header-menu__item
           a(href="#") menu

    main.l-main
      .l-main-inner
        = yield

app/views/trips/_form.html.slim
= form_for @trip do |f|
  - if @trip.errors.any?
    #error_explanation
      h2 = "#{pluralize(@trip.errors.count, "error")} prohibited this trip from being saved:"
      ul
        - @trip.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :from_date
    = f.date_select :from_date
  .field
    = f.label :to_date
    = f.date_select :to_date
  .actions = f.submit

app/views/trips/edit.html.slim
h1 Editing trip

== render 'form'

= link_to 'Show', @trip
'|
= link_to 'Back', trips_path

app/views/trips/index.html.slim
h2.heading 旅一覧

ul.trip-card-list
  li.trip-card(v-for="trip in trips")
    a(href="/trips/{{ trip.id }}")
      .trip-card__photo
        img(src="http://placehold.it/150x150")
      .trip-card__detail
        p.trip-card__title= "{{ trip.name }}"
        p.trip-card__date
          span from
          span -
          span to

  .trip-card-add
    input.trip-card__name(type="text" v-model="newTrip.name")
    input.trip-card__from-date(type="text")

  button.trip__add-btn(v-on:click="addTrip")
    | add new trip

app/views/trips/new.html.slim
h1 New trips

== render 'form'

= link_to 'Back', trips_path

app/views/trips/show.html.slim
p#notice = notice

p
  strong Title:
  = @trip.title
p
  strong Description:
  = @trip.description
p
  strong From date:
  = @trip.from_date
p
  strong To date:
  = @trip.to_date

= link_to 'Edit', edit_trip_path(@trip)
'|
= link_to 'Back', trips_path